name: Build LuaJIT for Windows

on:
  push:
    branches:
      - v2.1
  pull_request:
    branches:
      - v2.1
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [x86, x64] # 构建目标平台

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSVC environment
      run: |
        if ('${{ matrix.platform }}' -eq 'x86') {
          cmd /c C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat
        } else {
          cmd /c C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
        }

    - name: Clone LuaJIT repository
      run: |
        git clone https://github.com/yuhoocom/LuaJIT.git
        cd LuaJIT
        git checkout main # 确保我们在正确的分支上

    - name: Build LuaJIT for ${{ matrix.platform }}
      run: |
        cd LuaJIT/src
        msvcbuild

    - name: Upload LuaJIT binaries
      uses: actions/upload-artifact@v3
      with:
        name: luajit-${{ matrix.platform }}-binaries
        path: |
          LuaJIT/src/luajit.exe
