name: Build LuaJIT for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x86, x64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}

    - name: Build LuaJIT
      run: |
        cd src
        if [ "${{ matrix.arch }}" == "x86" ]; then
          nmake /f Makefile.msvc
        else
          nmake /f Makefile.msvc BUILDMODE=static
        fi

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: LuaJIT-${{ matrix.arch }}
        path: src/luajit.exe
